"use client";
import {useEffect,useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
import Link from 'next/link';
import {ArrowLeft,ArrowUp,ArrowDown,ArrowRight,CarFront,Map,ScrollText,Menu,X,Lock,Check,RotateCcw} from 'lucide-react';
import {useLanguage} from '@/components/LanguageProvider';
import {useAuth} from '@/hooks/useAuth';
import {fetchGameProgress} from '@/lib/game-account';
import {emptyProgress,type GameProgress} from '@/lib/game-missions';
import {loadGameSettings,storeGameSettings} from '@/lib/playground-settings';
import {GameAudio} from '@/lib/game-audio';
import {GameWelcome} from './GameWelcome';
import {GameLoading} from './GameLoading';
import type {createHub} from './hub-world';
import type {HubStation} from './hub-rules';
import type {HubStatus} from './hub-attractions';
import {HubControls} from './HubControls';
import '@fontsource/amatic-sc/latin-ext-400.css';
import '@fontsource/amatic-sc/latin-400.css';
import '@fontsource/nunito/latin-ext-400.css';
import '@fontsource/nunito/latin-400.css';
import './game-ui.css';
import './open-world.css';

function Atlas(){return <svg className="hub-atlas" viewBox="0 0 600 500" aria-hidden="true"><defs><pattern id="atlas-grid" width="30" height="30" patternUnits="userSpaceOnUse"><path d="M30 0H0V30" fill="none" stroke="#928ca4" strokeOpacity=".09"/></pattern></defs><path fill="#302b3d" d="M0 0h600v500H0z"/><path fill="url(#atlas-grid)" d="M0 0h600v500H0z"/><path d="M90 400L55 300 125 220 100 100 270 60 410 100 530 210 495 370 390 445 220 425Z" fill="#706f5b" stroke="#bab896" strokeWidth="2"/><path d="M75 280Q200 185 270 270T515 240" stroke="#414c62" strokeWidth="32" fill="none"/><path d="M180 340L265 355 350 300 420 180" stroke="#e5cda0" strokeWidth="4" strokeDasharray="8 9" fill="none"/>{[[180,340],[350,300],[420,180]].map(([x,y],i)=><g key={i}><circle cx={x} cy={y} r="14" fill="#c3e5ac" stroke="#25212c" strokeWidth="5"/><text x={x} y={y-27} textAnchor="middle" fill="#fcf3dc" fontSize="21" fontFamily="Amatic SC">{['COMMONS','LANTERN MEADOW','ENERGY GROVE'][i]}</text></g>)}{[0,1,2,3].map(i=><path key={i} d={`M${160+i*36} 175l18 -36 18 36Z`} fill="#c4b395"/>)}<text x="38" y="45" fill="#c2b7cc" fontFamily="Amatic SC" fontSize="26">SCRIPTICX / FIELD ATLAS</text><path d="M535 425v35m-15-17h30" stroke="#d6c9dc"/><text x="535" y="415" fill="#d6c9dc" textAnchor="middle">N</text></svg>;}
export default function OpenWorld(){
 const {locale}=useLanguage(),{user}=useAuth(),ro=locale==='ro',router=useRouter();
 const host=useRef<HTMLDivElement>(null),world=useRef<Awaited<ReturnType<typeof createHub>>|null>(null),dialog=useRef<HTMLDialogElement>(null),travelTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const audio=useRef<GameAudio|null>(null);
 const [status,setStatus]=useState<HubStatus>({district:'commons',checkpoint:1,lap:null,running:false});
 useEffect(()=>{audio.current=new GameAudio();return()=>audio.current?.dispose();},[]);
 const [welcome,setWelcome]=useState(true),[ready,setReady]=useState(false),[error,setError]=useState(false),[attempt,setAttempt]=useState(0),[near,setNear]=useState<HubStation|null>(null),[panel,setPanel]=useState<HubStation|'pause'|null>(null),[driving,setDriving]=useState(false),[nearCar,setNearCar]=useState(false),[leaving,setLeaving]=useState(false),[destination,setDestination]=useState<'meadow'|'grove'>('meadow'),[progress,setProgress]=useState<GameProgress>(emptyProgress),[progressError,setProgressError]=useState(false),[reduced,setReduced]=useState(false);
 useEffect(()=>{setReduced(loadGameSettings().reducedMotion);if(new URLSearchParams(window.location.search).get('resume')==='1')setWelcome(false);},[]);
 useEffect(()=>{const c=new AbortController();setProgress(emptyProgress);setProgressError(false);fetchGameProgress(c.signal).then(p=>{if(!c.signal.aborted)setProgress(p);}).catch(()=>{if(!c.signal.aborted)setProgressError(true);});return()=>c.abort();},[user?.id]);
 useEffect(()=>{const c=new AbortController();let active=true;setReady(false);setError(false);setNear(null);setNearCar(false);setDriving(false);import('./hub-world').then(m=>m.createHub(host.current!,c.signal,setNear,(d,n)=>{setDriving(d);setNearCar(n);},()=>setError(true),setStatus)).then(w=>{if(!active){w.dispose();return;}world.current=w;setReady(true);}).catch(()=>{if(active)setError(true);});return()=>{active=false;c.abort();world.current?.dispose();world.current=null;};},[attempt]);
 useEffect(()=>{world.current?.setPaused(welcome||panel!==null||leaving);world.current?.setCovered(welcome);},[welcome,panel,ready,leaving]);
 useEffect(()=>{if(panel)dialog.current?.showModal();else dialog.current?.close();},[panel]);
 useEffect(()=>{const blur=()=>{world.current?.setPaused(true);if(!welcome&&!leaving)setPanel(p=>p??'pause');};window.addEventListener('blur',blur);return()=>window.removeEventListener('blur',blur);},[welcome,leaving]);
 useEffect(()=>()=>{if(travelTimer.current)clearTimeout(travelTimer.current);},[]);
 function close(){setPanel(null);requestAnimationFrame(()=>host.current?.focus());}
 function openStation(){if(near&&!welcome&&!leaving&&!panel)setPanel(near);}
 function travel(){if(!near||panel==='pause'||!panel||leaving||(destination==='grove'&&!progress.completed.includes('lanterns')))return;setLeaving(true);setPanel(null);travelTimer.current=setTimeout(()=>router.push(`/play/island?zone=${destination}&from=commons`),reduced?0:650);}
 return <div className="sx-game hub-game" data-reduced-motion={reduced} onClickCapture={e=>{if(e.target instanceof Element&&e.target.closest('button:not(:disabled),a'))audio.current?.play('click',loadGameSettings());}}>
  {!welcome&&!panel&&<aside className="hub-district" aria-live="polite"><h2>{({commons:ro?'Piața exploratorilor':'Explorer’s commons',garden:ro?'Grădina vântului':'Wind garden',lake:ro?'Lacul oglinzilor':'Reflection lake',circuit:ro?'Circuitul roverului':'The motor loop'})[status.district]}</h2><p>{status.district==='commons'?(ro?'Nord: grădină · Vest: lac · Est: circuit':'North: garden · West: lake · East: circuit'):status.district==='garden'?(ro?'Apropie-te de sculpturi.':'Walk close to the sculptures.'):status.district==='lake'?(ro?'Un moment de liniște, lângă apă.':'Take a breath by the water.'):status.running?(ro?`Următoarea poartă: ${status.checkpoint} / 8`:`Next gate: ${status.checkpoint} / 8`):(ro?'Intră cu roverul prin poarta luminoasă.':'Drive the rover through the glowing gate.')}</p>{status.district==='circuit'&&status.lap!==null&&<strong>{ro?'Ultima tură':'Last lap'} · {status.lap.toFixed(1)}s</strong>}</aside>}
  <div ref={host} className="game-canvas" role="application" aria-label={ro?'Lumea ScripticX. WASD deplasare, F mașină, Tab interacțiune.':'ScripticX world. WASD to move, F for car, Tab to interact.'} tabIndex={welcome?-1:0} inert={welcome} onPointerDown={()=>host.current?.focus()} onKeyDown={e=>{const k=e.key.toLowerCase();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright','shift'].includes(k)){e.preventDefault();world.current?.input(k,true);}if(!e.repeat&&(k==='tab'||k==='e')&&near){e.preventDefault();openStation();}if(!e.repeat&&k==='f'){e.preventDefault();world.current?.vehicle();}if(!e.repeat&&k===' '){e.preventDefault();world.current?.jump();}if(k==='escape')setPanel('pause');}} onKeyUp={e=>world.current?.input(e.key.toLowerCase(),false)} onBlur={()=>['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright','shift'].forEach(k=>world.current?.input(k,false))}/>
  {!welcome&&!panel&&<><div className="hub-location"><span>SCRIPTICX / COMMONS</span><p>{ro?'Urmează-ți curiozitatea.':'Follow your curiosity.'}</p></div><button className="game-icon hub-menu" aria-label={ro?'Pauză':'Pause'} onClick={()=>setPanel('pause')}><Menu/></button><div className="game-dpad">{[{k:'w',I:ArrowUp},{k:'a',I:ArrowLeft},{k:'s',I:ArrowDown},{k:'d',I:ArrowRight}].map(({k,I},i)=><button key={k} className="game-icon" style={i===0?{gridColumn:2}:i===1?{gridColumn:1}:undefined} aria-label={{w:ro?'Înainte':'Forward',a:ro?'Stânga':'Left',s:ro?'Înapoi':'Backward',d:ro?'Dreapta':'Right'}[k]} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);world.current?.input(k,true);}} onPointerUp={()=>world.current?.input(k,false)} onPointerCancel={()=>world.current?.input(k,false)} onLostPointerCapture={()=>world.current?.input(k,false)}><I/></button>)}</div>{(nearCar||driving)&&<button className="hub-car game-button" onClick={()=>world.current?.vehicle()}><CarFront size={18}/>{driving?(ro?'Coboară':'Get out'):(ro?'Urcă la volan':'Drive rover')}<kbd>F</kbd></button>}
  <section className={`hub-preview ${near?'is-near':''}`} aria-hidden={!near}><div className="hub-preview-image"><Atlas/></div><div><span>{ro?'Ai descoperit un loc':'A place to discover'}</span><h2>{near==='quests'?(ro?'Jurnal de expediție':'Field missions'):(ro?'Harta lumii':'World atlas')}</h2><p>{near==='quests'?(ro?'Alege următoarea provocare.':'Find your next challenge.'):(ro?'Alege unde începe aventura.':'Choose where the adventure goes.')}</p><button tabIndex={near?0:-1} onClick={openStation}><kbd>Tab</kbd>{ro?'Deschide':'Explore'}<ArrowRight size={17}/></button></div></section></>}
  {welcome&&!error&&<GameWelcome ro={ro} reducedMotion={reduced} onPlay={()=>{setWelcome(false);requestAnimationFrame(()=>host.current?.focus());}} onSettings={()=>setPanel('pause')}/>}
  {!welcome&&(!ready||leaving)&&!error&&<GameLoading ro={ro}/>}
  {error&&<div className="game-loading" role="alert"><h1>{ro?'O mică pauză':'A little hiccup'}</h1><p>{ro?'Scena nu s-a putut încărca.':'The scene could not load.'}</p><button className="game-button" onClick={()=>setAttempt(a=>a+1)}>{ro?'Încearcă din nou':'Retry'}</button><Link href="/play">{ro?'Înapoi':'Back'}</Link></div>}
  <dialog ref={dialog} className={`hub-panel ${panel==='pause'?'hub-pause':''}`} onCancel={e=>{e.preventDefault();close();}} onClose={()=>setPanel(null)} aria-labelledby="hub-panel-title"><header><span>{panel==='map'?<Map/>:panel==='quests'?<ScrollText/>:<Menu/>} SCRIPTICX / {panel==='pause'?'COMMONS':'FIELD NOTES'}</span><button aria-label={ro?'Închide':'Close'} onClick={close}><X/></button></header>{panel==='pause'?<div className="hub-pause-content"><h1 id="hub-panel-title">{ro?'Un moment de răgaz.':'A moment to breathe.'}</h1><p>{ro?'Mergi la atlas pentru hartă și la panoul de misiuni pentru quest-uri. Urcă în rover cu F când ești lângă el.':'Walk to the atlas for the map and the mission board for quests. Press F beside the rover to drive.'}</p><HubControls ro={ro}/><button className="game-button game-primary" onClick={close}>{ro?'Continuă':'Continue'}</button><button className="game-button" onClick={()=>{world.current?.reset();close();}}><RotateCcw size={16}/>{ro?'Deblochează personajul':'Unstuck'}</button><label className="hub-small"><input type="checkbox" checked={reduced} onChange={e=>{const value=e.target.checked;setReduced(value);storeGameSettings({...loadGameSettings(),reducedMotion:value});setAttempt(a=>a+1);}}/> {ro?'Mișcare redusă':'Reduced motion'}</label><Link href="/play">{ro?'Înapoi la platformă':'Back to platform'}</Link></div>:<div className="hub-panel-grid"><Atlas/><div className="hub-destinations"><p className="game-eyebrow">{ro?'Următoarea destinație':'Next destination'}</p><h1 id="hub-panel-title">{panel==='quests'?(ro?'O idee aprinde lumea.':'An idea lights the world.'):(ro?'Unde mergem?':'Where shall we go?')}</h1>{progressError&&<p role="status">{ro?'Progres indisponibil. Destinațiile avansate rămân blocate.':'Progress unavailable. Advanced destinations remain locked.'}</p>}{(['meadow','grove'] as const).map((zone,i)=>{const locked=zone==='grove'&&!progress.completed.includes('lanterns');return <button key={zone} className={`hub-destination ${destination===zone?'selected':''}`} disabled={locked} onClick={()=>setDestination(zone)}><span>0{i+1}</span><div><strong>{zone==='meadow'?(ro?'Poiana felinarelor':'Lantern meadow'):(ro?'Crângul energiei':'Energy grove')}</strong><small>{zone==='meadow'?(ro?'Bucle · 500 puncte + fundal':'Loops · 500 points + background'):(ro?'Condiții și relee · două misiuni':'Conditions & relays · two missions')}</small></div>{locked?<Lock size={17}/>:progress.completed.includes(zone==='meadow'?'lanterns':'beacon')?<Check size={18}/>:<ArrowRight size={18}/>}</button>;})}<button className="game-button game-primary" onClick={travel} disabled={leaving}>{ro?'Pornește expediția':'Begin expedition'}<ArrowRight size={18}/></button><p className="hub-small">{ro?'Progresul și recompensele tale rămân salvate în cont.':'Your progress and rewards stay saved to your account.'}</p></div></div>}</dialog>
 </div>;
}
