import type {
  WorkshopResourceKind,
  WorkshopSectionKind,
  WorkshopStatus,
} from "@/lib/trainer-portal";

const en = {
  eyebrow: "Trainer portal",
  title: "Workshops",
  subtitle:
    "Plan the running order, keep every deck and game one click away, and take notes while you host.",
  backToAdmin: "Back to admin",
  backToWorkshops: "All workshops",

  newWorkshop: "New workshop",
  createTitle: "New workshop",
  createDescription:
    "Start with the essentials. The agenda, links, and games are added on the workshop page.",
  create: "Create workshop",
  created: "Workshop created.",
  cancel: "Cancel",
  save: "Save",
  saved: "Saved",
  saving: "Saving…",
  saveFailed: "Could not save the last change. Try again.",
  sharedNote: "Shared with all administrators",
  sharedHint:
    "Workshops are stored on the platform and are visible to every administrator.",
  errorTitle: "Could not load the workshops",
  errorDescription: "The request to the platform failed. Try again in a moment.",
  retry: "Try again",

  emptyTitle: "No workshops yet",
  emptyDescription: "Create one to start planning the running order.",
  notFoundTitle: "Workshop not found",
  notFoundDescription: "It may have been deleted by another administrator.",

  duplicate: "Duplicate",
  duplicateSuffix: "(copy)",
  duplicated: "Workshop duplicated as a draft.",
  deleteWorkshop: "Delete workshop",
  deleteWorkshopTitle: "Delete this workshop?",
  deleteWorkshopDescription:
    "The agenda, links, and notes are deleted for every administrator. This cannot be undone.",
  delete: "Delete",
  deleted: "Workshop deleted.",
  open: "Open",

  statTotal: "Workshops",
  statNext: "Next session",
  statNextNone: "Nothing scheduled",
  statPlanned: "Planned time",

  fieldTitle: "Title",
  fieldSummary: "Summary",
  fieldStartsAt: "Starts",
  fieldLocation: "Location",
  fieldAudience: "Audience",
  fieldTrainers: "Trainers",
  fieldTrainersHint: "Separate names with a comma.",
  fieldStatus: "Status",

  tabAgenda: "Agenda",
  tabResources: "Links and games",
  tabNotes: "Notes",
  tabDetails: "Details",

  agendaTitle: "Running order",
  sectionsLabel: "sections",
  agendaDescription:
    "Times are calculated from the start of the workshop, so changing one duration shifts the rest.",
  addSection: "Add section",
  editSection: "Edit section",
  newSection: "New section",
  fieldDuration: "Duration (minutes)",
  fieldKind: "Type",
  fieldOwner: "Led by",
  fieldNotes: "Trainer notes",
  attachedResources: "Attached links",
  attachHint: "Pick what you will open during this section.",
  noResourcesYet: "Add a link or a game first to attach it here.",
  moveUp: "Move up",
  moveDown: "Move down",
  markDone: "Mark as done",
  markNotDone: "Mark as not done",
  removeSection: "Remove section",
  agendaEmptyTitle: "No sections yet",
  agendaEmptyDescription: "Add the first block of the running order.",
  now: "Now",
  endsAt: "Ends at",
  copyRunSheet: "Copy run sheet",
  runSheetCopied: "Run sheet copied to the clipboard.",
  copyFailed: "Could not copy to the clipboard.",
  resetProgress: "Reset progress",
  progressLabel: "{done} of {total} sections done",

  resourcesDescription:
    "Canva decks, documentation, videos, and the games you run during the session.",
  addResource: "Add link",
  editResource: "Edit link",
  newResource: "New link",
  fieldUrl: "URL",
  fieldUrlHint: "Paste the share link. Canva decks can be previewed here.",
  fieldResourceNote: "How to use it",
  invalidUrl: "Enter a link starting with https://",
  removeResource: "Remove link",
  openLink: "Open",
  copyLink: "Copy link",
  linkCopied: "Link copied.",
  preview: "Preview",
  hidePreview: "Hide preview",
  resourcesEmptyTitle: "No links yet",
  resourcesEmptyDescription: "Add the deck you present from, or the first game.",
  filterAll: "All",
  usedInSections: "Used in {count} sections",
  usedInOneSection: "Used in 1 section",
  usedNowhere: "Not attached to the agenda",

  notesTitle: "Notes",
  notesDescription:
    "What to change next time, what the room needed, what went long.",
  notePlaceholder: "Write a note for the team…",
  addNote: "Add note",
  noteAdded: "Note added.",
  resolve: "Mark as handled",
  reopen: "Reopen",
  removeNote: "Delete note",
  notesEmptyTitle: "No notes yet",
  notesEmptyDescription: "Write down anything worth remembering for the next run.",
  openNotes: "{count} open",
  handled: "Handled",

  statuses: {
    draft: "Draft",
    scheduled: "Scheduled",
    delivered: "Delivered",
  } satisfies Record<WorkshopStatus, string>,

  sectionKinds: {
    talk: "Talk",
    demo: "Live demo",
    activity: "Exercise",
    game: "Game",
    break: "Break",
    qa: "Questions",
  } satisfies Record<WorkshopSectionKind, string>,

  resourceKinds: {
    canva: "Canva deck",
    slides: "Slides",
    game: "Game",
    doc: "Document",
    video: "Video",
    link: "Link",
  } satisfies Record<WorkshopResourceKind, string>,
};

export type TrainerPortalCopy = typeof en;

const ro: TrainerPortalCopy = {
  eyebrow: "Portal traineri",
  title: "Workshopuri",
  subtitle:
    "Planifică ordinea activităților, ține prezentările și jocurile la un click distanță și notează pe parcurs.",
  backToAdmin: "Înapoi la admin",
  backToWorkshops: "Toate workshopurile",

  newWorkshop: "Workshop nou",
  createTitle: "Workshop nou",
  createDescription:
    "Începe cu datele esențiale. Programul, linkurile și jocurile se adaugă în pagina workshopului.",
  create: "Creează workshopul",
  created: "Workshopul a fost creat.",
  cancel: "Anulează",
  save: "Salvează",
  saved: "Salvat",
  saving: "Se salvează…",
  saveFailed: "Ultima modificare nu a putut fi salvată. Încearcă din nou.",
  sharedNote: "Vizibil pentru toți administratorii",
  sharedHint:
    "Workshopurile sunt salvate pe platformă și sunt vizibile pentru toți administratorii.",
  errorTitle: "Workshopurile nu au putut fi încărcate",
  errorDescription: "Cererea către platformă a eșuat. Încearcă din nou în câteva momente.",
  retry: "Încearcă din nou",

  emptyTitle: "Niciun workshop",
  emptyDescription: "Creează unul ca să începi planificarea.",
  notFoundTitle: "Workshopul nu a fost găsit",
  notFoundDescription: "Este posibil să fi fost șters de alt administrator.",

  duplicate: "Duplică",
  duplicateSuffix: "(copie)",
  duplicated: "Workshopul a fost duplicat ca draft.",
  deleteWorkshop: "Șterge workshopul",
  deleteWorkshopTitle: "Ștergi acest workshop?",
  deleteWorkshopDescription:
    "Programul, linkurile și notițele sunt șterse pentru toți administratorii. Acțiunea nu poate fi anulată.",
  delete: "Șterge",
  deleted: "Workshopul a fost șters.",
  open: "Deschide",

  statTotal: "Workshopuri",
  statNext: "Următoarea sesiune",
  statNextNone: "Nimic programat",
  statPlanned: "Timp planificat",

  fieldTitle: "Titlu",
  fieldSummary: "Descriere",
  fieldStartsAt: "Începe",
  fieldLocation: "Locație",
  fieldAudience: "Participanți",
  fieldTrainers: "Traineri",
  fieldTrainersHint: "Separă numele cu virgulă.",
  fieldStatus: "Status",

  tabAgenda: "Program",
  tabResources: "Linkuri și jocuri",
  tabNotes: "Notițe",
  tabDetails: "Detalii",

  agendaTitle: "Ordinea activităților",
  sectionsLabel: "secțiuni",
  agendaDescription:
    "Orele sunt calculate din momentul de început, deci o durată modificată mută restul programului.",
  addSection: "Adaugă secțiune",
  editSection: "Editează secțiunea",
  newSection: "Secțiune nouă",
  fieldDuration: "Durată (minute)",
  fieldKind: "Tip",
  fieldOwner: "Susținut de",
  fieldNotes: "Notițe pentru trainer",
  attachedResources: "Linkuri atașate",
  attachHint: "Alege ce vei deschide în această secțiune.",
  noResourcesYet: "Adaugă întâi un link sau un joc ca să îl poți atașa aici.",
  moveUp: "Mută mai sus",
  moveDown: "Mută mai jos",
  markDone: "Marchează ca finalizată",
  markNotDone: "Marchează ca nefinalizată",
  removeSection: "Elimină secțiunea",
  agendaEmptyTitle: "Nicio secțiune",
  agendaEmptyDescription: "Adaugă primul bloc din program.",
  now: "Acum",
  endsAt: "Se termină la",
  copyRunSheet: "Copiază programul",
  runSheetCopied: "Programul a fost copiat în clipboard.",
  copyFailed: "Nu s-a putut copia în clipboard.",
  resetProgress: "Resetează progresul",
  progressLabel: "{done} din {total} secțiuni finalizate",

  resourcesDescription:
    "Prezentări Canva, documentație, materiale video și jocurile din timpul sesiunii.",
  addResource: "Adaugă link",
  editResource: "Editează linkul",
  newResource: "Link nou",
  fieldUrl: "Link",
  fieldUrlHint: "Lipește linkul de partajare. Prezentările Canva pot fi previzualizate aici.",
  fieldResourceNote: "Cum se folosește",
  invalidUrl: "Introdu un link care începe cu https://",
  removeResource: "Elimină linkul",
  openLink: "Deschide",
  copyLink: "Copiază linkul",
  linkCopied: "Link copiat.",
  preview: "Previzualizare",
  hidePreview: "Ascunde previzualizarea",
  resourcesEmptyTitle: "Niciun link",
  resourcesEmptyDescription: "Adaugă prezentarea din care susții sesiunea sau primul joc.",
  filterAll: "Toate",
  usedInSections: "Folosit în {count} secțiuni",
  usedInOneSection: "Folosit într-o secțiune",
  usedNowhere: "Neatașat programului",

  notesTitle: "Notițe",
  notesDescription:
    "Ce schimbi data viitoare, de ce a avut nevoie sala, ce a durat mai mult.",
  notePlaceholder: "Scrie o notiță pentru echipă…",
  addNote: "Adaugă notița",
  noteAdded: "Notița a fost adăugată.",
  resolve: "Marchează ca rezolvată",
  reopen: "Redeschide",
  removeNote: "Șterge notița",
  notesEmptyTitle: "Nicio notiță",
  notesEmptyDescription: "Notează orice merită reținut pentru sesiunea următoare.",
  openNotes: "{count} deschise",
  handled: "Rezolvată",

  statuses: {
    draft: "Draft",
    scheduled: "Programat",
    delivered: "Susținut",
  },

  sectionKinds: {
    talk: "Prezentare",
    demo: "Demo live",
    activity: "Exercițiu",
    game: "Joc",
    break: "Pauză",
    qa: "Întrebări",
  },

  resourceKinds: {
    canva: "Prezentare Canva",
    slides: "Slide-uri",
    game: "Joc",
    doc: "Document",
    video: "Video",
    link: "Link",
  },
};

export function trainerPortalCopy(locale: string): TrainerPortalCopy {
  return locale === "ro" ? ro : en;
}
